#!/bin/sh

PLUGIN="x86"
MANUAL="mle-x86.7"

PREFIX="${PREFIX:-/usr/local}"
PREFIX_MAN_DIR="${PREFIX}/share/man/man7"
PREFIX_SHARE_MLE_DIR="${PREFIX}/share/mle"

set -e

usage()
{
	printf "usage: setup {install|uninstall}\n"
}

install()
{
	set -x

	mkdir -p "${PREFIX_SHARE_MLE_DIR}"
	cp "src/${PLUGIN}" "${PREFIX_SHARE_MLE_DIR}/"

	mkdir -p "${PREFIX_MAN_DIR}"
	cp "doc/${MANUAL}" "${PREFIX_MAN_DIR}/"
}

uninstall()
{
	set -x
	rm -r "${PREFIX_SHARE_MLE_DIR}/${PLUGIN}" \
	      "${PREFIX_MAN_DIR}/${MANUAL}"
}

main()
{
	case $# in
	(1)
		case $1 in
		("install")
			install
			;;

		("uninstall")
			uninstall
			;;

		(*)
			usage
			;;
		esac
		;;

	(*)
		usage
		;;
	esac
}

main "$@"
